import random

students = [
    "سید محمد احمدی",
    "علیرضا دلخواهی",
    "مهدی شهیدی",
    "رضا چوکیان",
    "پوریا صامتی",
    "محمدحسین شاهنده",
    "سید محمدرضا خسروشاهی",
    "محمد ترکمان",
    "محمدمهدی صالحی مرگان",
    "آرش کرمی",
    "علی پیروی بستان آباد",
    "محمدرضا حسینی",
    "امیرعلی داراب پور",
    "میثم نصرتی آذر",
    "همایون پیش یار",
    "مهراب محمدحسینی",
    "علی اسماعیل نژاد",
    "رضا دباغی",
    "سید امیرحسین هاشمی",
    "مصطفی رشادی",
    "محمد وصالی",
    "مبین آتشی",
    "مجتبی فاضلی",
    "کیارش فضلی",
    "سعید علیدادیانی",
    "محمدحسن علیزاده",
    "آرمان کاظمی",
    "مهدی ذوالفقاری",
    "علیرضا هدایت نیا",
    "مسعود ماپار",
    "مهدی جلالوند",
    "محمد نسیمی",
    "مجید نبی لو",
    "امیرحسین بهرامی کوتنایی",
    "محمدعلی جاسم زاده",
    "سید سجاد صفا",
    "علیرضا حمیدانی",
    "محمد پویا جلالی",
    "جلال الدین کرامتی نژاد",
    "جعفر قدرتی",
    "شایان صادقی",
    "مهدی خطیریان",
    "علیرضا عباسی",
    "سید امید خاتمی",
    "امیرحسین بلوک اصلی",
    "میثم خراسانی",
]

py_str_methods = [
    'capitalize',
    'casefold',
    'center',
    'count',
    'encode',
    'endswith',
    'expandtabs',
    'find',
    'format',
    'format_map',
    'index',
    'isalnum',
    'isalpha',
    'isascii',
    'isdecimal',
    'isdigit',
    'isidentifier',
    # 'islower',
    'isnumeric',
    # 'isprintable',
    'isspace',
    'istitle',
    # 'isupper',
    'join',
    # 'ljust',
    # 'lower',
    # 'lstrip',
    'maketrans',
    'partition',
    # 'removeprefix',
    # 'removesuffix',
    'replace',
    # 'rfind',
    # 'rindex',
    # 'rjust',
    # 'rpartition',
    # 'rsplit',
    # 'rstrip',
    'split',
    'splitlines',
    'startswith',
    'strip',
    'swapcase',
    'title',
    'translate',
    # 'upper',
    'zfill'
]
py_str_methods = list(map(lambda s: f"str.{s}", py_str_methods))

py_builtin_funcs = [
    'filter',
    'enumerate',
    # 'round',
    'bin',
    'sorted',
    'zip',
    'eval',
    'chr',
    'any',
    'hex',
    'reversed',
    # 'divmod',
    'exec',
    'ord',
    'all',
    # 'oct',
    'format',
]

random.shuffle(students)

to_search = py_str_methods + py_builtin_funcs
result = list(zip(students, to_search))
for s,f in filter(lambda x: not x[1].startswith("str."), result):
    print(s, '->', f)

print()
for s,f in filter(lambda x: x[1].startswith("str."), result):
    print(s, '->', f)
